app1/urls.py
from django.urls import path
from app1.views import *
app_name='app1'
urlpatterns=[
    path('file1/',file1,name='file1'),
]

app2/urls.py
from django.urls import path
from app2.views import *
app_name='app2'
urlpatterns=[
    path('file2/',file2,name='file2'),
]

project15/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2
from app3.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
    path('file3/',file3,name='file3')
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app3/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def file1(request):
    return render(request,'file1.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def file2(request):
    return render (request,'file2.html')

app3/views.py
from django.shortcuts import render

# Create your views here.
def file3(request):
    return render(request,'file3.html')

templates/file1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>
             HI WELCOME TO THE FIRST FILE
        </h1>
        <a href="{% url 'app2:file2' %}">GOT TO FILE2</a><br>
        <a href="{% url 'file3' %}"> GOT TO FILE3</a>

    </center>
    
</body>
</html>

templates/file2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>
             HI WELCOME TO THE  SECOND FILE
        </h1>
        <a href="{% url 'app1:file1' %}">GOT TO FILE1</a><br>
        <a href="{% url 'file3' %}">GOT TO FILE3</a>


        
    </center>
    
    
</body>
</html>

templates/file3.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    <center>
        <h1>
             HI WELCOME TO THE THIRD FILE
        </h1>
        <a href="{% url 'app2:file2' %}">GOT TO FILE2</a><br>
        <a href="{% url 'app1:file1' %}">GOT TO FILE1</a>
        
    </center>
    
    
</body>
</html>